### ISSUE TITLE
run grpcui and got "Symbol not found: grpc.health.v1.Health"

### ISSUE THREAD

**Issue by plong009** [fullstorydev/grpcui#82] opened 2020-08-03 03:52 UTC
hello,
I run grpcui 1.0.0 release on Windows and it failed.
    E:\>grpcui.exe -plaintext 127.0.0.1:50051
    Failed to compute set of methods to expose: Symbol not found: grpc.health.v1.Health

but there is a grpc.health.v1.Health service, grpcurl can list it out.
    E:\>grpcurl.exe -plaintext 127.0.0.1:50051 list
    grpc.health.v1.Health
    grpc.reflection.v1alpha.ServerReflection
    my_grpc.my_grpc_service

the service is wroten c++, almost same as the grpc example greeter_server.cc,
does anyone known how to resolve this issue?
thank you!

**Comment by plong009** [comment] 2020-08-03 04:03
looks like it's grpc.health.v1.Health issue, grpcurl also can't list methods.
    E:\>grpcurl.exe -plaintext 127.0.0.1:50051 list grpc.health.v1.Health
    Failed to list methods for service "grpc.health.v1.Health": Symbol not found: grpc.health.v1.Health

sorry, 
please close the issue.

**Comment by jhump** [comment] 2020-08-03 16:35
@plong009, can you take a look at #40 and see if the suggestion there helps? The issue observed there was that a linker optimization discarded some of the data that is needed at runtime for reflection to work properly. That issue indicates linker options when building the C++ server that may help.

**Comment by jhump** [comment] 2022-02-14 16:14
This is a duplicate of #40. Also, I  believe it is fixed as of #160 as thus fixed in the next release.

I think it's possible that the root cause was the server's reflection implementation providing unexpected extra files in the response, and the reflection conflict making incorrect assumptions about the order of those files. Also see https://github.com/jhump/protoreflect/issues/466.

**Closed by jhump** 2022-02-14 16:14 UTC
