### ISSUE TITLE
Option to set the host and port from the web UI

### ISSUE THREAD

**Issue by Kernald** [fullstorydev/grpcui#48] opened 2019-08-25 23:37 UTC
At the moment, the host and port need to be specified on the command line, which makes it impossible to deploy an instance of gRPC UI somewhere and just use it when needed (at least if you work with multiple projects/environments).

**Comment by sheepdreamofandroids** [comment] 2020-02-14 10:15
This would be a great enhancement.

The way I see it, there is no need to create any user interface for this. Simply allow a request parameter when opening the page to indicate a host and port. Something like 
`http://grpcui.test.cluster/?server=grpcservice.test.cluster:8980`

My usecase would be to deploy one instance of grpcui on our testcluster and have each service link to that ui with the proper parameter set up.

**Comment by jhump** [comment] 2020-02-19 14:49
I like this idea, but it seems like there would be many query string parameters we need to support for this to really be right -- basically all of the command-line options that control _how_ the connection is established/dialed would need to be encode-able in query string parameters.

Adding a UI for that would be simple if all it did was collect input and then build the query string -- so that when you click "Dial" (or whatever the button is called), it would just go to the main UI page, but with all of the relevant query string params set based on the input form.

**Comment by jhump** [comment] 2020-02-19 14:49
I am closing this issue because it is a duplicate of #14.

**Closed** 2020-02-19 16:21 UTC
