### ISSUE TITLE
Add -H command line option to add default request headers

### ISSUE THREAD

**Issue by jp-clumio** [fullstorydev/grpcui#106] opened 2021-01-27 19:12 UTC
Grpcui and grpcurl are super cool tools. One thing, I have to do manually often is, filling in a request header with bearer token to connect to our grpc services.  

It would be easier to reuse if the default header could be added as a command line option. The default headers could populate the initial form when the UI opens up. This would make it easy to rerun the previous command or add a script to fill the headers and so on.

To parallel grpcurl, `-H [REQUEST_HEADER] ` would be intuitive as well.

**Comment by jhump** [comment] 2021-01-27 21:52
This appears to be a duplicate of #85 and was addressed in #88. It was then released in [v1.1.0](https://github.com/fullstorydev/grpcui/releases/tag/v1.1.0).

Run `grpcui -h` and then take a look at the `-default-header` argument. I think it is exactly what you are looking for.

**Closed by jhump** 2021-01-27 21:52 UTC

**Comment by jp-clumio** [comment] 2021-01-28 05:28
Thanks.
