### ISSUE TITLE
Deploy grpcui with the grpc service

### ISSUE THREAD

**Issue by ameetchhatwal** [fullstorydev/grpcui#52] opened 2019-10-07 18:42 UTC
The grpc ui works great and I am able to access my service, but I am looking for a an alternate solution of if there is a way to deploy the toll with my grpc service itself, so that anyone can readily access it rather than every person install the tool locally. 

What changes will I need to do to achieve that. Any anyone tried anything similar?

**Comment by jhump** [comment] 2019-10-08 17:29
@ameetchhatwal: Is this a duplicate of #53? If not, can you clarify the difference here?

FWIW, from a simple reading of your paragraph above, I'd say you can easily just deploy grpcui _with_ your server (running alongside it, like on the same VM or in the same pod if using Kubernetes) and expose it to users. That way you don't need people to install/run the tool locally: they can just access the running copy that is co-located with the server via their browser.

**Comment by ameetchhatwal** [comment] 2019-10-08 17:37
@jhump yes this is a duplicate issue to #53. The above represents what I want to achieve, and then on researching it looked like standalone application is the I had to use, so I opened the issue #53. Is that correct? Can you please elaborate of how can one deploy grpcui with existing GRPC service?

**Comment by jhump** [comment] 2019-10-08 17:43
> Can you please elaborate of how can one deploy grpcui with existing GRPC service?

Just run it as a sidecar and have it talk to your server via loopback. So you'd give a `localhost:<port>` address to grpcui when you run it this way. Your deploy tooling would need to be able to deploy and stop/start both programs (the main server and the sidecar). How to do that is beyond the scope of this project since it depends on how you deploy things. In Kubernetes, you could easily create a deployment that runs two containers for each replica: your gRPC server and grpcui. (In Kubernetes, two containers in the same pod can communicate over loopback.)

You would access grpcui the same way you access the gRPC server: something in your infrastructure would need to expose it somehow (like putting it behind a load balancer). Again, with Kubernetes as an example, you would just need to define the ports that the deployment exposes, and Kubernetes will handle routing requests to the two different ports to the two different containers in the pod.

**Closed by jhump** 2019-10-08 17:43 UTC
