### ISSUE TITLE
Request metadata is not loaded when load history

### ISSUE THREAD

**Issue by kajebiii** [fullstorydev/grpcui#86] opened 2020-09-17 10:49 UTC
Hi, i am big fan of grpcui.

I am using a lot of request (that include sort of request-metadatas).
So I use history loading feature many times.

But request-metadata is not loading. And it is very inconvenient for me.

Reproduce step
- Send request with request metadata
![image](https://user-images.githubusercontent.com/32012515/93461420-b1c4f980-f91f-11ea-82a2-8888c763c07b.png)
- Click history and load (we can key metadata list in this page)
![image](https://user-images.githubusercontent.com/32012515/93461475-c43f3300-f91f-11ea-93b8-5217cc9fca2d.png)
- Request metdata disappear
![image](https://user-images.githubusercontent.com/32012515/93461525-d4571280-f91f-11ea-8589-ca0672fe0443.png)

**Comment by jhump** [comment] 2020-09-17 12:08
This is duplicate of #84

**Closed by jhump** 2020-09-17 12:08 UTC
